name: autodeploy

on: [push]

jobs:
  autodeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pack CLI via the official buildpack Action
        uses: buildpacks/github-actions/setup-pack@v5.0.0

      - name: Build app with pack CLI & publish to GitHub Container Registry
        run: |
          pack build ghcr.io/bjoernNF/backend:latest \
              --builder paketobuildpacks/builder:base \
              --path . \
              --env "BP_OCI_SOURCE=https://github.com/BjoernNF/backend" \
              --env "BP_JVM_VERSION=17" \
              --cache-image ghcr.io/BjoernNF/backend:latest \
              --publish